// invite.service.js
// Manages invite codes generated by super admins for new tenants
// (and for trial → paid conversion).

const crypto = require('crypto');
const { supabaseAdmin } = require('../config/supabase');

const TABLE = 'invite_codes';
const DEFAULT_EXPIRY_DAYS = 30;
const PLAN_MAX_EMPLOYEES = {
  starter: 10,
  growth: 50,
  business: 200,
  enterprise: 1000,
  trial: 5,
};

// generateInviteCode — creates a unique alphanumeric code (12 chars) and
// inserts a row in invite_codes.
async function generateInviteCode(
  plan,
  maxEmployees,
  generatedBy,
  expiryDays = DEFAULT_EXPIRY_DAYS,
) {
  if (!plan) throw new Error('plan is required');
  const cap = maxEmployees || PLAN_MAX_EMPLOYEES[plan] || 10;
  const expiresAt = new Date(Date.now() + expiryDays * 24 * 60 * 60 * 1000);

  for (let attempt = 0; attempt < 5; attempt += 1) {
    const code = randomCode(12);
    const { data, error } = await supabaseAdmin
      .from(TABLE)
      .insert({
        code,
        plan,
        max_employees: cap,
        generated_by: generatedBy || null,
        expires_at: expiresAt.toISOString(),
        is_used: false,
      })
      .select('*')
      .single();

    if (!error) return data;
    if (!String(error.message || '').toLowerCase().includes('duplicate')) {
      throw new Error(`generateInviteCode failed: ${error.message}`);
    }
  }
  throw new Error('generateInviteCode: exhausted retries on code collision');
}

// validateInviteCode — confirms the code exists, is unused, and not expired.
async function validateInviteCode(code) {
  if (!code) {
    return { valid: false, reason: 'Code is required' };
  }
  const { data, error } = await supabaseAdmin
    .from(TABLE)
    .select('*')
    .eq('code', code)
    .maybeSingle();

  if (error) return { valid: false, reason: 'Lookup failed' };
  if (!data) return { valid: false, reason: 'Invalid code' };
  if (data.is_used) return { valid: false, reason: 'Code already redeemed' };
  if (data.expires_at && new Date(data.expires_at) < new Date()) {
    return { valid: false, reason: 'Code has expired' };
  }
  return { valid: true, invite: data };
}

// redeemInviteCode — marks code as used and links it to a tenant.
async function redeemInviteCode(code, tenantId, redeemedBy) {
  const check = await validateInviteCode(code);
  if (!check.valid) {
    throw new Error(check.reason);
  }
  const { data, error } = await supabaseAdmin
    .from(TABLE)
    .update({
      is_used: true,
      redeemed_at: new Date().toISOString(),
      redeemed_by: redeemedBy || null,
      tenant_id: tenantId,
    })
    .eq('code', code)
    .eq('is_used', false)
    .select('*')
    .single();

  if (error || !data) {
    throw new Error(`redeemInviteCode failed: ${error?.message || 'race'}`);
  }
  return data;
}

// generateTrialCode — short-lived code (7 days) used when converting a trial
// account to a paid tenant.
async function generateTrialCode(plan = 'starter', generatedBy = null) {
  return generateInviteCode(
    plan,
    PLAN_MAX_EMPLOYEES[plan] || 10,
    generatedBy,
    7,
  );
}

// listInviteCodes — super-admin view with optional filters.
// filters: { plan, isUsed, expired, limit, offset }
async function listInviteCodes(filters = {}) {
  let query = supabaseAdmin
    .from(TABLE)
    .select('*', { count: 'exact' })
    .order('generated_at', { ascending: false });

  if (filters.plan) query = query.eq('plan', filters.plan);
  if (typeof filters.isUsed === 'boolean') {
    query = query.eq('is_used', filters.isUsed);
  }
  if (filters.expired === true) {
    query = query.lt('expires_at', new Date().toISOString());
  } else if (filters.expired === false) {
    query = query.gte('expires_at', new Date().toISOString());
  }

  const limit = Math.min(parseInt(filters.limit || '100', 10), 1000);
  const offset = parseInt(filters.offset || '0', 10);
  query = query.range(offset, offset + limit - 1);

  const { data, error, count } = await query;
  if (error) throw new Error(`listInviteCodes failed: ${error.message}`);
  return { codes: data || [], total: count || 0, limit, offset };
}

function randomCode(length) {
  // Crockford-style alphabet: omits 0/O/1/I/L for legibility.
  const alphabet = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  const bytes = crypto.randomBytes(length);
  let out = '';
  for (let i = 0; i < length; i += 1) {
    out += alphabet[bytes[i] % alphabet.length];
  }
  return out;
}

module.exports = {
  generateInviteCode,
  validateInviteCode,
  redeemInviteCode,
  generateTrialCode,
  listInviteCodes,
  PLAN_MAX_EMPLOYEES,
};
